package service_keys

import (
	"crypto"
	"crypto/rsa"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gddisney/ultimate_db"
	"github.com/gddisney/webauthnext"
	"github.com/google/go-tpm/legacy/tpm2"
)

// ServiceKeyManager handles TPM-backed machine identities
type ServiceKeyManager struct {
	Provider *webauthnext.Provider
	DB       *ultimate_db.DB
}

// RegisterServiceIdentity binds an agent to the identity stack.
// tpmPublicBytes must be the raw byte slice of a TPM2B_PUBLIC structure generated by the agent's TPM.
func (s *ServiceKeyManager) RegisterServiceIdentity(name string, tpmPublicBytes []byte) error {
	// 1. Validate that the provided bytes are a legitimate TPM 2.0 Public Key structure
	_, err := tpm2.DecodePublic(tpmPublicBytes)
	if err != nil {
		return fmt.Errorf("failed to decode TPM2B_PUBLIC structure: %w", err)
	}

	// 2. Store the raw TPM bytes as the WebAuthn ID.
	user := &webauthnext.PasskeyUser{
		ID:          tpmPublicBytes,
		Name:        name,
		DisplayName: "Service: " + name,
	}
	
	val, err := json.Marshal(user)
	if err != nil { return err }

	txn := s.DB.BeginTxn()
	err = s.DB.Write(webauthnext.AuthPageID, txn, []byte("user:"+name), val, 0)
	s.DB.CommitTxn(txn)
	
	return err
}

// VerifyServiceSession is a middleware that enforces DBSC hardware pinning via TPM signatures.
func (s *ServiceKeyManager) VerifyServiceSession(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		proof := r.Header.Get("X-DBSC-Hardware-Proof")
		if proof == "" {
			http.Error(w, "Hardware proof required", http.StatusUnauthorized)
			return
		}

		// Parse the proof (Format: Name:Nonce:SignatureBase64)
		parts := strings.SplitN(proof, ":", 3)
		if len(parts) != 3 {
			http.Error(w, "Malformed DBSC proof", http.StatusBadRequest)
			return
		}
		serviceName, nonce, sigBase64 := parts[0], parts[1], parts[2]

		// 1. Fetch the registered TPM Service Identity
		txn := s.DB.BeginTxn()
		userBytes, err := s.DB.Read(webauthnext.AuthPageID, txn, []byte("user:"+serviceName))
		s.DB.CommitTxn(txn)

		if err != nil || len(userBytes) == 0 {
			http.Error(w, "Service identity not found", http.StatusUnauthorized)
			return
		}

		var user webauthnext.PasskeyUser
		if err := json.Unmarshal(userBytes, &user); err != nil {
			http.Error(w, "Corrupted identity record", http.StatusInternalServerError)
			return
		}

		// 2. Decode the stored TPM2B_PUBLIC structure
		tpmPubKey, err := tpm2.DecodePublic(user.ID)
		if err != nil {
			http.Error(w, "Failed to parse stored TPM key", http.StatusInternalServerError)
			return
		}

		cryptoKey, err := tpmPubKey.Key()
		if err != nil {
			http.Error(w, "Failed to extract cryptographic key", http.StatusInternalServerError)
			return
		}

		// 3. Decode the signature sent by the agent
		signature, err := base64.StdEncoding.DecodeString(sigBase64)
		if err != nil {
			http.Error(w, "Invalid signature encoding", http.StatusBadRequest)
			return
		}

		// 4. Verify the DBSC Signature
		payload := fmt.Sprintf("%s|%s", nonce, r.URL.Path)
		payloadHash := sha256.Sum256([]byte(payload))

		rsaPubKey, ok := cryptoKey.(*rsa.PublicKey)
		if !ok {
			http.Error(w, "Unsupported TPM key type (expected RSA)", http.StatusInternalServerError)
			return
		}

		err = rsa.VerifyPKCS1v15(rsaPubKey, crypto.SHA256, payloadHash[:], signature)
		if err != nil {
			http.Error(w, "Hardware signature verification failed", http.StatusForbidden)
			return
		}

		// 5. Time-based nonce check
		var timestamp int64
		fmt.Sscanf(nonce, "%d", &timestamp)
		if time.Now().Unix()-timestamp > 60 {
			http.Error(w, "DBSC Proof expired", http.StatusForbidden)
			return
		}

		next(w, r)
	}
}
